# Generated by Django 5.0.3 on 2024-03-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='uuid',
            field=models.UUIDField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
